# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# azure-pipelines.yml
trigger:
  branches:
    include:
      - master  # Triggers the pipeline on every push to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Choose the latest Ubuntu image for the build

steps:
  - task: Go@0
    inputs:
      version: '1.20'  # Go version you want to use
  
  - script: |
      go mod tidy   # Cleans up dependencies
      go build -o main .  # Builds the Go application
    displayName: 'Build Go Application'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)  # Path to publish build artifacts
      artifactName: 'drop'
      publishLocation: 'Container'  # Specifies where to publish artifacts (e.g., Azure Storage)


