# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:

  repositories:
    - repository: snehathankam
      type: github
      name: snehathankam/snehaProject  # Ensure this is the correct repository name
      ref: refs/heads/master  # Specify the branch name or commit SHA if needed
      endpoint: 'snehaProjectGithubServiceConnection'
  #containers:
    #- container: myContainer
    #  image: spportfolio.azurecr.io/userapi:$(Build.BuildId)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SUBSCRIPTION: 'snehaProjectACRServiceConnection'
  ACR_NAME: 'spportfolio'
  APP_SERVICE_NAME: 'spPortfolioApp'
  IMAGE_NAME: 'userapi'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildDockerImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(AZURE_SUBSCRIPTION)
        repository: $(ACR_NAME)/$(IMAGE_NAME)
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToAppService
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        appName: $(APP_SERVICE_NAME)
        imageName: $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)

